create table if not exists flowers (
  id text primary key,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price > 0),
  occasion text not null default 'general',
  image text not null default '',
  image_focus_x numeric(5, 2) not null default 50 check (image_focus_x >= 0 and image_focus_x <= 100),
  image_focus_y numeric(5, 2) not null default 50 check (image_focus_y >= 0 and image_focus_y <= 100),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id text primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null default '',
  customer_address text not null,
  payment_method text not null default 'cash' check (payment_method in ('cash', 'paypal')),
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed')),
  total numeric(10, 2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

alter table if exists orders
  add column if not exists customer_phone text not null default '';
alter table if exists orders
  add column if not exists payment_method text not null default 'cash';
alter table if exists orders
  add column if not exists payment_status text not null default 'pending';
alter table if exists flowers
  add column if not exists image_focus_x numeric(5, 2) not null default 50;
alter table if exists flowers
  add column if not exists image_focus_y numeric(5, 2) not null default 50;

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  flower_id text not null,
  name text not null,
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) not null check (line_total >= 0)
);

create table if not exists users (
  id text primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id text primary key,
  title text not null,
  message text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists site_settings (
  id text primary key,
  hero_image text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists idx_flowers_created_at on flowers (created_at desc);
create index if not exists idx_orders_created_at on orders (created_at desc);
create index if not exists idx_order_items_order_id on order_items (order_id);
create index if not exists idx_users_email on users (email);
create index if not exists idx_notifications_created_at on notifications (created_at desc);
create index if not exists idx_site_settings_updated_at on site_settings (updated_at desc);
